[workspace]
resolver = "2"

[package]
description = "Git Repository Update Tool"
edition = "2024"
include = [
  "Cargo.toml",
  "src/**/*"
]
name = "update_repository"
publish = false
rust-version = "1.90.0"
version = "1.0.0"

[[bin]]
name = "up-repo"
path = "src/main.rs"

